config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'site#about'
  get '/contact' => 'site#contact' 
  get '/admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'

  resources :items

  root 'site#about'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_cart_details
  
  def set_cart_details
    cart = session[:cart]
    @total_price = 0
    
    if(cart)
    @total_items = session[:cart].size
    cart.each do| id, quantity|
    item = Item.find_by_id(id)
    @total_price += quantity * item.price
  end
    
  else
    @total_items = 0
end 
end
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    
    cart = session[:cart] ||= {}
    cart[id] = (cart[id] || 0) + 1
        
    redirect_to :action => :index
  end

  def index
    @cart = session[:cart] || {}
  end
  
  def change
  cart = session[:cart]
  id = params[:id];
  quantity = params[:quantity].to_i
  if cart and cart[id]
    unless quantity <= 0
      cart[id] = quantity
    else
      cart.delete id
    end
  end
    redirect_to :action => :index
  end
  
  def checkout
    flash[:notice] = "CHECKOUT IS NOT IMPLEMENTED YET!!!"
    redirect_to :action => :index
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login
  end

  def admin_login
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Admin user successfully logged in, cart reset."
    redirect_to :controller => :items
  end

  def logout
    session[:login] = nil
    session[:cart] = nil
    flash[:notice] = "User logged out, cart reset."
    redirect_to :controller => :items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %>
    <p>Your Cart is empty.</p>
<% end %>

<% total = 0 %>
	
<table class="cart">
    <tr class="bgdcol2">
        <td class="legend"></td>
        <td class="legend">Item</td>
        <td class="legend">Price</td>
        <td class="legend">Qty</td>
        <td class="legend">Total</td>
    </tr>
	
<% @cart.each do | id, quantity | %>
    <% item = Item.find_by_id(id) %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
            </div>
        </td>
        <td class="title"><%= link_to item.title, item %></td>
        <td class="price"><%= number_to_currency(item.price) %></td>
        <td class="quantity"><%= quantity %><br /></td>
        <td class="cartprice">
        <%= number_to_currency(quantity * item.price, :unit => "€") %>
    </td>
    </tr>
    <% total += quantity * item.price %>
<% end %>

    <tr>
        <td colspan="4" class="bgdcol1">
            <div class="total">Total:</div>
        </td>
        <td class="bgdcol1">
            <div class="totalprice"><%= number_to_currency(total, :unit => "€") %></div>
        </td>
    </tr>
</table>

<p>
     <%= link_to 'Continue Shopping', :controller => :items %>
</p>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<table class="catalog">

<% @items.each do |item| %>
  <div class="itemstyle">
    
        <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:258px; width:258px"), item %>
        </div>
    
        <div class="title">
            <%= link_to item.title, item %>
        </div>
        <div class="description">
            <%=h item.description %>
        </div>
        <div class="price">
            <%= number_to_currency(item.price, :unit => "€") %>
        </div>
        <div class="links">
            <% if session[:login] == 1 %>
              <%= link_to 'Edit', edit_item_path(item) %> |
              <%= link_to 'Delete', item, :confirm => 'Are you sure?', :method => :delete %>
            <% else %>
              <a href="/cart/<%= item.id %>">Add to Cart</a><br><br>
            <% end %>

        </div>
   </div>
<% end %>
</table>
    <p><%= link_to 'New item', new_item_path %></p>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %> |
<a href="/cart/<%= @item.id %>">Add to Cart</a> 

app/views/layouts/_footer.html.erb
<div id=footer>
  <%= link_to "Graffotos", root_path, id: "logo" %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Graffotos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Graffotos", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/items">Products</a></li>
          <li><a href="/contact">Contact Us</a></li>
          <li><a href="/admin">Login</a></li>
          <li><a href="/logout">Logout</a></li>
          <li><a href="/cart">View Cart(<%=@total_items%> items, €<%=@total_price%>)</a></li> 
        </ul>
      </nav>
    </div>
  </header>
    
  <div id='container'>
    <div id='content'>
  		<%= yield %>
    </div>
    <!--<div id='first-column'>
    	<div class="searchbox">
    		<h2 class="BoxHeaders">Search</h2>
    		<input type="text" name="search" /><input type="submit" value="Search" />
    	</div>
      <div class="box">
        <h2 class="BoxHeaders">Special Offers</h2>
        <img src="/assets/Books/Pict1.jpg" name="Rotating" id="Rotating1" alt="Special Offers	">
    		<script type="text/javascript">
    			RotateImages(1,0);
    		</script>
    	</div>
    	<div class="box">
    		<h2 class="BoxHeaders">Newly Published</h2>
    		<img src="/assets/Books/Pict1.jpg" alt="New Books">
    	</div>
    </div>-->
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/site/about.html.erb
<div id="pic1"></div>
<h1>Premium stock photography from Graffotos</h1>
<p>Most of the photos on Graffoto have never been used in commercial campaigns before. 
Be the first one to experience the amazing quality of top-notch photographers.</p>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>